### ISSUE TITLE
npm install fails with a 404

### ISSUE THREAD

**Issue by noonat** [joshfire/angela#2]
I just discovered Angela this morning, and wanted to try it out. But when I run `npm install angela`, I get this:

``` bash
$ npm install angela
npm ERR! fetch failed https://registry.npmjs.org/angela/-/angela-1.1.0.tgz
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/fetch.js:58:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1598:14
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:105:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "angela"
npm ERR! cwd /Users/nathano
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.13
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/nathano/npm-debug.log
npm ERR! not ok code 0
```

Not sure if this is an npm issue or an angela issue, but thought you should know.

**Comment by tidoust** [comment]
Hi @noonat ,

Thanks for the report. That's weird. No idea what happened but I just `npm publish`-ed Angela again and that seems to have fixed the broken link.

**Comment by nicolsc** [comment]
:closed_lock_with_key:
